require('plugged')
require('settings')
require('keymaps')

require('language-server/completion')
require('language-server/diagnostics')
require('language-server/navigation')
require('language-server/config')

require('plugins/buftabline')
require('plugins/ctrlp')
require('plugins/easyclip')
require('plugins/editorconfig')
require('plugins/fugitive')
require('plugins/gitgutter')
require('plugins/indentline')
require('plugins/javascript')
require('plugins/json')
require('plugins/jsx')
require('plugins/markdown')
require('plugins/neoformat')
require('plugins/nerdcommenter')
require('plugins/nerdtree')
require('plugins/typescript')
require('plugins/symbolsoutline')

require('tools/buffer-management')
require('tools/convert-indentation')
require('tools/cpp-utils')
require('tools/convert-indentation')
require('tools/quickfix-interaction')
require('tools/general-info')
require('tools/ranger-integration')
require('tools/reload-screen')
require('tools/safe-close')
require('tools/safe-save')
require('tools/search-in-files')
require('tools/yank-path')
